<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>9 Measurement Error, Meta-analysis and Missing Values | MCMCglmm Course Notes</title>
  <meta name="description" content="Extended documentation and course notes for the MCMCglmm R package." />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="9 Measurement Error, Meta-analysis and Missing Values | MCMCglmm Course Notes" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Extended documentation and course notes for the MCMCglmm R package." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="9 Measurement Error, Meta-analysis and Missing Values | MCMCglmm Course Notes" />
  
  <meta name="twitter:description" content="Extended documentation and course notes for the MCMCglmm R package." />
  

<meta name="author" content="Jarrod Hadfield" />


<meta name="date" content="2026-03-17" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="pedigree.html"/>
<link rel="next" href="path.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="libs/rglWebGL-binding-1.3.36/rglWebGL.js"></script>
<link href="libs/rglwidgetClass-1.3.36/rgl.css" rel="stylesheet" />
<script src="libs/rglwidgetClass-1.3.36/rglClass.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/utils.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/buffer.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/subscenes.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/shaders.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/shadersrc.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/textures.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/projection.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/mouse.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/init.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/pieces.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/draw.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/controls.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/selection.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/rglTimer.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/pretty.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/axes.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/animation.src.js"></script>
<script src="libs/CanvasMatrix4-1.3.36/CanvasMatrix.src.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="overview.html"><a href="overview.html"><i class="fa fa-check"></i><b>1</b> Overview</a>
<ul>
<li class="chapter" data-level="1.1" data-path="overview.html"><a href="overview.html#outline"><i class="fa fa-check"></i><b>1.1</b> Outline</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="bayesian.html"><a href="bayesian.html"><i class="fa fa-check"></i><b>2</b> Bayesian Analysis and MCMC</a>
<ul>
<li class="chapter" data-level="2.1" data-path="bayesian.html"><a href="bayesian.html#introduction"><i class="fa fa-check"></i><b>2.1</b> Introduction</a></li>
<li class="chapter" data-level="2.2" data-path="bayesian.html"><a href="bayesian.html#likelihood"><i class="fa fa-check"></i><b>2.2</b> Likelihood</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="bayesian.html"><a href="bayesian.html#maximum-likelihood-ml"><i class="fa fa-check"></i><b>2.2.1</b> Maximum Likelihood (ML)</a></li>
<li class="chapter" data-level="2.2.2" data-path="bayesian.html"><a href="bayesian.html#restricted-maximum-likelihood-reml"><i class="fa fa-check"></i><b>2.2.2</b> Restricted Maximum Likelihood (REML)</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="bayesian.html"><a href="bayesian.html#prior-distribution"><i class="fa fa-check"></i><b>2.3</b> Prior Distribution</a></li>
<li class="chapter" data-level="2.4" data-path="bayesian.html"><a href="bayesian.html#posterior-distribution"><i class="fa fa-check"></i><b>2.4</b> Posterior Distribution</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="bayesian.html"><a href="bayesian.html#marginal-posterior-distribution"><i class="fa fa-check"></i><b>2.4.1</b> Marginal Posterior Distribution</a></li>
<li class="chapter" data-level="2.4.2" data-path="bayesian.html"><a href="bayesian.html#intervals-sec"><i class="fa fa-check"></i><b>2.4.2</b> Credible Intervals</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="bayesian.html"><a href="bayesian.html#MCMC"><i class="fa fa-check"></i><b>2.5</b> MCMC</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="bayesian.html"><a href="bayesian.html#starting-values"><i class="fa fa-check"></i><b>2.5.1</b> Starting values</a></li>
<li class="chapter" data-level="2.5.2" data-path="bayesian.html"><a href="bayesian.html#metropolis-hastings-updates"><i class="fa fa-check"></i><b>2.5.2</b> Metropolis-Hastings updates</a></li>
<li class="chapter" data-level="2.5.3" data-path="bayesian.html"><a href="bayesian.html#gibbs-sampling"><i class="fa fa-check"></i><b>2.5.3</b> Gibbs Sampling</a></li>
<li class="chapter" data-level="2.5.4" data-path="bayesian.html"><a href="bayesian.html#diagnostics-sec"><i class="fa fa-check"></i><b>2.5.4</b> MCMC Diagnostics</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="bayesian.html"><a href="bayesian.html#Vprior-sec"><i class="fa fa-check"></i><b>2.6</b> Priors for Residual Variances</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="bayesian.html"><a href="bayesian.html#IP-sec"><i class="fa fa-check"></i><b>2.6.1</b> Improper Priors</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="bayesian.html"><a href="bayesian.html#transform-sec"><i class="fa fa-check"></i><b>2.7</b> Transformations</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="glm.html"><a href="glm.html"><i class="fa fa-check"></i><b>3</b> Linear and Generalised Linear Models</a>
<ul>
<li class="chapter" data-level="3.1" data-path="glm.html"><a href="glm.html#linear-model-lm"><i class="fa fa-check"></i><b>3.1</b> Linear Model (LM)</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="glm.html"><a href="glm.html#lm-sec"><i class="fa fa-check"></i><b>3.1.1</b> Linear Predictors</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="glm.html"><a href="glm.html#generalised-linear-model-glm"><i class="fa fa-check"></i><b>3.2</b> Generalised Linear Model (GLM)</a></li>
<li class="chapter" data-level="3.3" data-path="glm.html"><a href="glm.html#poisglm-sec"><i class="fa fa-check"></i><b>3.3</b> Poisson GLM</a></li>
<li class="chapter" data-level="3.4" data-path="glm.html"><a href="glm.html#od-sec"><i class="fa fa-check"></i><b>3.4</b> Overdispersion</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="glm.html"><a href="glm.html#multiplicative-overdispersion"><i class="fa fa-check"></i><b>3.4.1</b> Multiplicative Overdispersion</a></li>
<li class="chapter" data-level="3.4.2" data-path="glm.html"><a href="glm.html#addod-sec"><i class="fa fa-check"></i><b>3.4.2</b> Additive Overdispersion</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="glm.html"><a href="glm.html#prediction-in-glm"><i class="fa fa-check"></i><b>3.5</b> Prediction in GLM</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="glm.html"><a href="glm.html#posterior-predictive-distribution"><i class="fa fa-check"></i><b>3.5.1</b> Posterior Predictive Distribution</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="glm.html"><a href="glm.html#binom-sec"><i class="fa fa-check"></i><b>3.6</b> Binomial and Bernoulli GLM</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="glm.html"><a href="glm.html#od-binom"><i class="fa fa-check"></i><b>3.6.1</b> Overdispersion</a></li>
<li class="chapter" data-level="3.6.2" data-path="glm.html"><a href="glm.html#binom-pred-sec"><i class="fa fa-check"></i><b>3.6.2</b> Prediction</a></li>
<li class="chapter" data-level="3.6.3" data-path="glm.html"><a href="glm.html#bernoulli-sec"><i class="fa fa-check"></i><b>3.6.3</b> Bernoulli GLM</a></li>
<li class="chapter" data-level="3.6.4" data-path="glm.html"><a href="glm.html#probit-link"><i class="fa fa-check"></i><b>3.6.4</b> Probit link</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="glm.html"><a href="glm.html#ordinal-sec"><i class="fa fa-check"></i><b>3.7</b> Ordinal Data</a></li>
<li class="chapter" data-level="3.8" data-path="glm.html"><a href="glm.html#non-zero-binomial-data"><i class="fa fa-check"></i><b>3.8</b> Non-zero Binomial Data</a></li>
<li class="chapter" data-level="3.9" data-path="glm.html"><a href="glm.html#sec-complete-separation"><i class="fa fa-check"></i><b>3.9</b> Complete Separation</a>
<ul>
<li class="chapter" data-level="3.9.1" data-path="glm.html"><a href="glm.html#gelman-prior-sec"><i class="fa fa-check"></i><b>3.9.1</b> The <span class="citation">Gelman, Jakulin, et al. (2008)</span> prior</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="ranef.html"><a href="ranef.html"><i class="fa fa-check"></i><b>4</b> Random effects</a>
<ul>
<li class="chapter" data-level="4.1" data-path="ranef.html"><a href="ranef.html#GLMM"><i class="fa fa-check"></i><b>4.1</b> Generalised Linear Mixed Model (GLMM)</a></li>
<li class="chapter" data-level="4.2" data-path="ranef.html"><a href="ranef.html#ranpred-sec"><i class="fa fa-check"></i><b>4.2</b> Prediction with Random Effects</a></li>
<li class="chapter" data-level="4.3" data-path="ranef.html"><a href="ranef.html#overdispersed-binomial-as-a-bernoulli-glmm"><i class="fa fa-check"></i><b>4.3</b> Overdispersed Binomial as a Bernoulli GLMM</a></li>
<li class="chapter" data-level="4.4" data-path="ranef.html"><a href="ranef.html#ICC"><i class="fa fa-check"></i><b>4.4</b> Intra-class Correlations</a></li>
<li class="chapter" data-level="4.5" data-path="ranef.html"><a href="ranef.html#sec-underdispersion"><i class="fa fa-check"></i><b>4.5</b> Underdispersion</a></li>
<li class="chapter" data-level="4.6" data-path="ranef.html"><a href="ranef.html#PXprior-sec"><i class="fa fa-check"></i><b>4.6</b> Priors for Random Effect Variances</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="ranef.html"><a href="ranef.html#f-and-folded-t-priors"><i class="fa fa-check"></i><b>4.6.1</b> <span class="math inline">\(F\)</span> and folded-<span class="math inline">\(t\)</span> priors</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="ranef.html"><a href="ranef.html#Vprior-gen-sec"><i class="fa fa-check"></i><b>4.7</b> Prior Generators</a></li>
<li class="chapter" data-level="4.8" data-path="ranef.html"><a href="ranef.html#priors-on-functions-of-variances"><i class="fa fa-check"></i><b>4.8</b> Priors on Functions of Variances</a>
<ul>
<li class="chapter" data-level="4.8.1" data-path="ranef.html"><a href="ranef.html#intra-class-correlation"><i class="fa fa-check"></i><b>4.8.1</b> Intra-class Correlation</a></li>
</ul></li>
<li class="chapter" data-level="4.9" data-path="ranef.html"><a href="ranef.html#fix-or-rand"><i class="fa fa-check"></i><b>4.9</b> Fixed or Random?</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="cat-int.html"><a href="cat-int.html"><i class="fa fa-check"></i><b>5</b> Categorical Random Interactions</a>
<ul>
<li class="chapter" data-level="5.1" data-path="cat-int.html"><a href="cat-int.html#vstruct-sec"><i class="fa fa-check"></i><b>5.1</b> Variance Structures</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="cat-int.html"><a href="cat-int.html#idh-sec"><i class="fa fa-check"></i><b>5.1.1</b> <span class="math inline">\(\texttt{idh}\)</span> Variance Structure</a></li>
<li class="chapter" data-level="5.1.2" data-path="cat-int.html"><a href="cat-int.html#us-sec"><i class="fa fa-check"></i><b>5.1.2</b> <span class="math inline">\(\texttt{us}\)</span> Variance Structure</a></li>
<li class="chapter" data-level="5.1.3" data-path="cat-int.html"><a href="cat-int.html#other-variance-structures"><i class="fa fa-check"></i><b>5.1.3</b> Other Variance Structures</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="cat-int.html"><a href="cat-int.html#link-func-sec"><i class="fa fa-check"></i><b>5.2</b> Linking Functions</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="cat-int.html"><a href="cat-int.html#textttstr-covariances-between-random-terms"><i class="fa fa-check"></i><b>5.2.1</b> <span class="math inline">\(\texttt{str}\)</span>: covariances between random terms</a></li>
<li class="chapter" data-level="5.2.2" data-path="cat-int.html"><a href="cat-int.html#multim-sec"><i class="fa fa-check"></i><b>5.2.2</b> <span class="math inline">\(\texttt{mm}\)</span>: multi-membership models</a></li>
<li class="chapter" data-level="5.2.3" data-path="cat-int.html"><a href="cat-int.html#textttcovu-covariances-between-random-and-residual-terms"><i class="fa fa-check"></i><b>5.2.3</b> <span class="math inline">\(\texttt{covu}\)</span>: covariances between random and residual terms</a></li>
<li class="chapter" data-level="5.2.4" data-path="cat-int.html"><a href="cat-int.html#texttttheta_scale-scaled-linear-predictor"><i class="fa fa-check"></i><b>5.2.4</b> <span class="math inline">\(\texttt{theta_scale}\)</span>: scaled linear predictor</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="cat-int.html"><a href="cat-int.html#VCVprior-sec"><i class="fa fa-check"></i><b>5.3</b> Priors for Covariance Matrices</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="cat-int.html"><a href="cat-int.html#marginal-priors-for-variances"><i class="fa fa-check"></i><b>5.3.1</b> Marginal Priors for Variances</a></li>
<li class="chapter" data-level="5.3.2" data-path="cat-int.html"><a href="cat-int.html#VCVprior-r-sec"><i class="fa fa-check"></i><b>5.3.2</b> Marginal Priors for Covariances and Correlations</a></li>
<li class="chapter" data-level="5.3.3" data-path="cat-int.html"><a href="cat-int.html#full-joint-prior"><i class="fa fa-check"></i><b>5.3.3</b> Full joint prior</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="cont-int.html"><a href="cont-int.html"><i class="fa fa-check"></i><b>6</b> Continuous Random Interactions</a>
<ul>
<li class="chapter" data-level="6.1" data-path="cont-int.html"><a href="cont-int.html#random-regression"><i class="fa fa-check"></i><b>6.1</b> Random Regression</a></li>
<li class="chapter" data-level="6.2" data-path="cont-int.html"><a href="cont-int.html#het-res"><i class="fa fa-check"></i><b>6.2</b> Heterogeneous (Residual) Variances</a></li>
<li class="chapter" data-level="6.3" data-path="cont-int.html"><a href="cont-int.html#autoc-sec"><i class="fa fa-check"></i><b>6.3</b> Autocorrelation</a></li>
<li class="chapter" data-level="6.4" data-path="cont-int.html"><a href="cont-int.html#vstab-sec"><i class="fa fa-check"></i><b>6.4</b> Variance stabilisation</a></li>
<li class="chapter" data-level="6.5" data-path="cont-int.html"><a href="cont-int.html#ante-sec"><i class="fa fa-check"></i><b>6.5</b> Antedependence and Autoregressive Models</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="cont-int.html"><a href="cont-int.html#autoregressive-models"><i class="fa fa-check"></i><b>6.5.1</b> Autoregressive Models</a></li>
<li class="chapter" data-level="6.5.2" data-path="cont-int.html"><a href="cont-int.html#prior-ante-sec"><i class="fa fa-check"></i><b>6.5.2</b> Priors in Antedependence models</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="cont-int.html"><a href="cont-int.html#user-defined-sec"><i class="fa fa-check"></i><b>6.6</b> User-defined Design Matrices</a></li>
<li class="chapter" data-level="6.7" data-path="cont-int.html"><a href="cont-int.html#splines"><i class="fa fa-check"></i><b>6.7</b> Splines</a></li>
<li class="chapter" data-level="6.8" data-path="cont-int.html"><a href="cont-int.html#penalised-signal-regression"><i class="fa fa-check"></i><b>6.8</b> Penalised Signal Regression</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="multi.html"><a href="multi.html"><i class="fa fa-check"></i><b>7</b> Multi-response Models</a>
<ul>
<li class="chapter" data-level="7.1" data-path="multi.html"><a href="multi.html#multi-response-non-gaussian-models"><i class="fa fa-check"></i><b>7.1</b> Multi-response Non-Gaussian Models</a></li>
<li class="chapter" data-level="7.2" data-path="multi.html"><a href="multi.html#multi-response-bernoulli-models"><i class="fa fa-check"></i><b>7.2</b> Multi-response Bernoulli Models</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="multi.html"><a href="multi.html#bern-gaus-sec"><i class="fa fa-check"></i><b>7.2.1</b> Bernoulli-Gaussian</a></li>
<li class="chapter" data-level="7.2.2" data-path="multi.html"><a href="multi.html#all-bernoulli"><i class="fa fa-check"></i><b>7.2.2</b> All Bernoulli</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="multi.html"><a href="multi.html#sec-longwide"><i class="fa fa-check"></i><b>7.3</b> Wide versus Long Format</a></li>
<li class="chapter" data-level="7.4" data-path="multi.html"><a href="multi.html#covu-sec"><i class="fa fa-check"></i><b>7.4</b> Covariances between random and residual terms (<span class="math inline">\(\texttt{covu}\)</span>)</a></li>
<li class="chapter" data-level="7.5" data-path="multi.html"><a href="multi.html#scaled-linear-predictors-texttttheta_scale"><i class="fa fa-check"></i><b>7.5</b> Scaled linear predictors: <span class="math inline">\(\texttt{theta_scale}\)</span></a></li>
<li class="chapter" data-level="7.6" data-path="multi.html"><a href="multi.html#multinomial-models"><i class="fa fa-check"></i><b>7.6</b> Multinomial Models</a></li>
<li class="chapter" data-level="7.7" data-path="multi.html"><a href="multi.html#zero-modified-poisson-models"><i class="fa fa-check"></i><b>7.7</b> Zero-modified Poisson Models</a>
<ul>
<li class="chapter" data-level="7.7.1" data-path="multi.html"><a href="multi.html#zero-inflated-poisson"><i class="fa fa-check"></i><b>7.7.1</b> Zero-inflated Poisson</a></li>
<li class="chapter" data-level="7.7.2" data-path="multi.html"><a href="multi.html#Hurdle"><i class="fa fa-check"></i><b>7.7.2</b> Hurdle Poisson models</a></li>
<li class="chapter" data-level="7.7.3" data-path="multi.html"><a href="multi.html#ZAP"><i class="fa fa-check"></i><b>7.7.3</b> Zero-altered Poisson Models</a></li>
</ul></li>
<li class="chapter" data-level="7.8" data-path="multi.html"><a href="multi.html#zero-modified-binomial-models"><i class="fa fa-check"></i><b>7.8</b> Zero-modified Binomial Models</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="pedigree.html"><a href="pedigree.html"><i class="fa fa-check"></i><b>8</b> Structured Random Effects</a>
<ul>
<li class="chapter" data-level="8.1" data-path="pedigree.html"><a href="pedigree.html#pedigree-sec"><i class="fa fa-check"></i><b>8.1</b> Pedigrees</a></li>
<li class="chapter" data-level="8.2" data-path="pedigree.html"><a href="pedigree.html#phylogenies"><i class="fa fa-check"></i><b>8.2</b> Phylogenies</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="pedigree.html"><a href="pedigree.html#nodestips"><i class="fa fa-check"></i><b>8.2.1</b> <code>nodes="TIPS"</code></a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="pedigree.html"><a href="pedigree.html#user-defined-covariance-structures"><i class="fa fa-check"></i><b>8.3</b> User-defined covariance structures</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="measurement.html"><a href="measurement.html"><i class="fa fa-check"></i><b>9</b> Measurement Error, Meta-analysis and Missing Values</a>
<ul>
<li class="chapter" data-level="9.1" data-path="measurement.html"><a href="measurement.html#missing-values-in-the-response"><i class="fa fa-check"></i><b>9.1</b> Missing values in the response</a></li>
<li class="chapter" data-level="9.2" data-path="measurement.html"><a href="measurement.html#censored-response-variables"><i class="fa fa-check"></i><b>9.2</b> Censored response variables</a></li>
<li class="chapter" data-level="9.3" data-path="measurement.html"><a href="measurement.html#meta-sec"><i class="fa fa-check"></i><b>9.3</b> Meta-analysis and error in the response</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="measurement.html"><a href="measurement.html#sec-meta-exact"><i class="fa fa-check"></i><b>9.3.1</b> Exact meta-analysis</a></li>
<li class="chapter" data-level="9.3.2" data-path="measurement.html"><a href="measurement.html#sec-meta-alternatives"><i class="fa fa-check"></i><b>9.3.2</b> <span class="math inline">\(\texttt{mev}\)</span>, <span class="math inline">\(\texttt{units}\)</span> structure and <span class="math inline">\(\texttt{ginverse}\)</span></a></li>
<li class="chapter" data-level="9.3.3" data-path="measurement.html"><a href="measurement.html#multivariate-meta-analysis"><i class="fa fa-check"></i><b>9.3.3</b> Multivariate meta-analysis</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="measurement.html"><a href="measurement.html#interval-data"><i class="fa fa-check"></i><b>9.4</b> Interval Data</a></li>
<li class="chapter" data-level="9.5" data-path="measurement.html"><a href="measurement.html#error-in-the-predictors"><i class="fa fa-check"></i><b>9.5</b> Error in the predictors</a>
<ul>
<li class="chapter" data-level="9.5.1" data-path="measurement.html"><a href="measurement.html#classical-and-berkson-errors."><i class="fa fa-check"></i><b>9.5.1</b> Classical and Berkson errors.</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="path.html"><a href="path.html"><i class="fa fa-check"></i><b>10</b> Path Analysis &amp; Antedependence Structures</a>
<ul>
<li class="chapter" data-level="10.1" data-path="path.html"><a href="path.html#path-anlaysis"><i class="fa fa-check"></i><b>10.1</b> Path Anlaysis</a></li>
<li class="chapter" data-level="10.2" data-path="cont-int.html"><a href="cont-int.html#ante-sec"><i class="fa fa-check"></i><b>10.2</b> Antedependence</a></li>
<li class="chapter" data-level="10.3" data-path="path.html"><a href="path.html#scaling"><i class="fa fa-check"></i><b>10.3</b> Scaling</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="technical-details.html"><a href="technical-details.html"><i class="fa fa-check"></i><b>11</b> Technical Details</a>
<ul>
<li class="chapter" data-level="11.1" data-path="technical-details.html"><a href="technical-details.html#model-form"><i class="fa fa-check"></i><b>11.1</b> Model Form</a></li>
<li class="chapter" data-level="11.2" data-path="technical-details.html"><a href="technical-details.html#MCMC-app"><i class="fa fa-check"></i><b>11.2</b> MCMC Sampling Schemes</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="technical-details.html"><a href="technical-details.html#updating-the-latent-variables-bf-l"><i class="fa fa-check"></i><b>11.2.1</b> Updating the latent variables <span class="math inline">\({\bf l}\)</span></a></li>
<li class="chapter" data-level="11.2.2" data-path="technical-details.html"><a href="technical-details.html#updating-the-location-vector-boldsymboltheta-leftboldsymbolmathbfbeta-bf-uright"><i class="fa fa-check"></i><b>11.2.2</b> Updating the location vector <span class="math inline">\(\boldsymbol{\theta} = \left[{\boldsymbol{\mathbf{\beta}}}^{&#39;}\; {\bf u}^{&#39;}\right]^{&#39;}\)</span></a></li>
<li class="chapter" data-level="11.2.3" data-path="technical-details.html"><a href="technical-details.html#updating-the-variance-structures-bf-g-and-bf-r"><i class="fa fa-check"></i><b>11.2.3</b> Updating the variance structures <span class="math inline">\({\bf G}\)</span> and <span class="math inline">\({\bf R}\)</span></a></li>
<li class="chapter" data-level="11.2.4" data-path="technical-details.html"><a href="technical-details.html#ordinal-models"><i class="fa fa-check"></i><b>11.2.4</b> Ordinal Models</a></li>
<li class="chapter" data-level="11.2.5" data-path="technical-details.html"><a href="technical-details.html#path-analyses"><i class="fa fa-check"></i><b>11.2.5</b> Path Analyses</a></li>
<li class="chapter" data-level="11.2.6" data-path="technical-details.html"><a href="technical-details.html#deviance-and-dic"><i class="fa fa-check"></i><b>11.2.6</b> Deviance and DIC</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="technical-details.html"><a href="technical-details.html#parameter-expansion"><i class="fa fa-check"></i><b>11.3</b> Parameter Expansion</a></li>
<li class="chapter" data-level="11.4" data-path="technical-details.html"><a href="technical-details.html#priors-for-corg-and-corgh-structures"><i class="fa fa-check"></i><b>11.4</b> Priors for <code>corg</code> and <code>corgh</code> structures</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i><b>12</b> References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">MCMCglmm Course Notes</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="measurement" class="section level1 hasAnchor" number="9">
<h1><span class="header-section-number">9</span> Measurement Error, Meta-analysis and Missing Values<a href="measurement.html#measurement" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Variables in the model may not be perfectly observed. In the worst case they are completely missing, but often we have some information about their possible or likely value. We may only know the interval in which the value lies, in which case the observation is said to be censored. In other cases, we have a ‘best’ estimate of the value, but this estimate comes with error. Handling incomplete information about an observation is relatively straightforward when the observation is a response variable since, but considerably more challenging when the observation is a predictor.</p>
<div id="missing-values-in-the-response" class="section level2 hasAnchor" number="9.1">
<h2><span class="header-section-number">9.1</span> Missing values in the response<a href="measurement.html#missing-values-in-the-response" class="anchor-section" aria-label="Anchor link to header"></a></h2>
</div>
<div id="censored-response-variables" class="section level2 hasAnchor" number="9.2">
<h2><span class="header-section-number">9.2</span> Censored response variables<a href="measurement.html#censored-response-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A censored observation is not perfectly known, but we do know it lies between two possible values. If the lower possible value is not known we say we have left censoring and if the upper possible value is not known we say we have right censoring. When both the lower and upper possible values are known we have interval censoring. This terminology is not required when dealing with censoring in <span class="math inline">\(\texttt{MCMCglmm}\)</span> - all that is required is specifying the lower and upper possible values. With left censoring we simply set the lower possible value to minus infinity and with right censoring we simply set the upper possible value to minus infinity. If the observation is perfectly observed we would make the lower and upper possible values equal, and if the observation is completely missing we set the lower and upper possible values to minus and plus infinity, respectively (or use <span class="math inline">\(\texttt{NA}\)</span>). As an example, we will use the <span class="math inline">\(\texttt{IR_diabetes}\)</span> data from the package <span class="math inline">\(\texttt{icenReg}\)</span> which contains information about the time between the onset of diabetes and the development of diabetic nephropathy in 731 patients.</p>
<div class="sourceCode" id="cb353"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb353-1"><a href="measurement.html#cb353-1" tabindex="-1"></a><span class="fu">data</span>(IR_diabetes)</span>
<span id="cb353-2"><a href="measurement.html#cb353-2" tabindex="-1"></a><span class="fu">head</span>(IR_diabetes)</span></code></pre></div>
<pre><code>##   left right gender
## 1   24    27   male
## 2   22    22 female
## 3   37    39   male
## 4   20    20   male
## 5    1    16   male
## 6    8    20 female</code></pre>
<p>The columns <span class="math inline">\(\texttt{left}\)</span> and <span class="math inline">\(\texttt{right}\)</span> give the minimum and maximum amount of time per patient (units aren’t given, but I presume years). For the majority of patients (81%) the amount of time is known perfectly (for example the second patient) but for some patients the time is interval censored (for example the first patient). In <span class="math inline">\(\texttt{MCMCglmm}\)</span> the lower and upper censoring points are passed using <span class="math inline">\(\texttt{cbind}\)</span> and the chosen response is prefixed with <span class="math inline">\(\texttt{cen}\)</span>:</p>
<div class="sourceCode" id="cb355"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb355-1"><a href="measurement.html#cb355-1" tabindex="-1"></a>m.cens<span class="ot">&lt;-</span><span class="fu">MCMCglmm</span>(<span class="fu">cbind</span>(left, right)<span class="sc">~</span>gender, <span class="at">data=</span>IR_diabetes, <span class="at">family=</span><span class="st">&quot;cengaussian&quot;</span>)</span>
<span id="cb355-2"><a href="measurement.html#cb355-2" tabindex="-1"></a><span class="fu">summary</span>(m.cens)</span></code></pre></div>
<pre><code>## 
##  Iterations = 3001:12991
##  Thinning interval  = 10
##  Sample size  = 1000 
## 
##  DIC: 3876.685 
## 
##  R-structure:  ~units
## 
##       post.mean l-95% CI u-95% CI eff.samp
## units     38.34    34.45    42.24     1000
## 
##  Location effects: cbind(left, right) ~ gender 
## 
##             post.mean l-95% CI u-95% CI eff.samp  pMCMC    
## (Intercept)   16.1266  15.4139  16.8657     1000 &lt;0.001 ***
## gendermale     1.1932   0.2121   2.1080     1000  0.012 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Censoring is implemented for the Poisson, Gaussian and exponential distributions.</p>
</div>
<div id="meta-sec" class="section level2 hasAnchor" number="9.3">
<h2><span class="header-section-number">9.3</span> Meta-analysis and error in the response<a href="measurement.html#meta-sec" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In reality, the true value is never really known for continuous variables - there will always be some discrepancy between the true value and its measured value. Usually we ignore this, and indeed, if the magnitude of the discrepancies have constant probability over observations, there is little to be gained from worrying about it - these discrepancies become part of the residual and the assumption of homogeneity of variance will still hold. In some cases, however, the magnitude of the discrepancies may vary over observations. In such cases there is an advantage to modelling the discrepancies since it allows us to give more weight to observations that have smaller discrepancies. To leverage this information we first need to assume (or know) what distribution these discrepancies follow. In this section we will start by assuming the discrepancies are normally distributed. Second, we need to know (at least up to proportionality) the expected variance of the discrepancies for each observation, something I’ll refer to as the measurement error variance. The most common situation in which we have this information is when the observation is an <em>estimate</em> of some quantity and the measurement error variance is taken to be the standard error of the estimate squared. In such situations, the model is often referred to as a meta-analysis. To illustrate we will analyse data collected from studies looking at the effectiveness of coaching on the performance on the Scholastic Aptitude Test (SAT). The data are in <span class="math inline">\(\texttt{dat.kalaian1996}\)</span> from the package <span class="math inline">\(\texttt{metadat}\)</span>:</p>
<div class="sourceCode" id="cb357"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb357-1"><a href="measurement.html#cb357-1" tabindex="-1"></a><span class="fu">data</span>(dat.kalaian1996)</span>
<span id="cb357-2"><a href="measurement.html#cb357-2" tabindex="-1"></a><span class="fu">head</span>(dat.kalaian1996[,<span class="dv">2</span><span class="sc">:</span><span class="dv">8</span>])</span></code></pre></div>
<pre><code>##                   study year n1i n2i outcome    yi     vi
## 1 Alderman &amp; Powers (A) 1980  28  22  verbal  0.22 0.0817
## 2 Alderman &amp; Powers (B) 1980  39  40  verbal  0.09 0.0507
## 3 Alderman &amp; Powers (C) 1980  22  17  verbal  0.14 0.1045
## 4 Alderman &amp; Powers (D) 1980  48  43  verbal  0.14 0.0442
## 5 Alderman &amp; Powers (E) 1980  25  74  verbal -0.01 0.0535
## 6 Alderman &amp; Powers (F) 1980  37  35  verbal  0.14 0.0557</code></pre>
<p>We will focus on the variable <span class="math inline">\(\texttt{yi}\)</span> which is the standardised mean difference in SAT scores between coached and uncoached students. The difference is standardised by the pooled standard deviation<a href="#fn44" class="footnote-ref" id="fnref44"><sup>44</sup></a> and positive values indicate the coached students have higher scores. 27 studies contribute one observation - either for the verbal or math subtest (indicated by <span class="math inline">\(\texttt{outcome}\)</span>) whereas 20 studies contribute two observations, one for verbal and one for math. The variable <span class="math inline">\(\texttt{vi}\)</span> is the standard error squared of this difference - the assumed measurement error variance. A plot of <span class="math inline">\(\texttt{yi}\)</span> against the precision (<span class="math inline">\(1/\sqrt{\texttt{vi}}\)</span>) is known as a funnel plot (Figure <a href="measurement.html#fig:funnel">9.1</a>):</p>
<div class="figure"><span style="display:block;" id="fig:funnel"></span>
<img src="_bookdown_files/fig/funnel-1.png" alt="Standardised mean difference in SAT scores between coached and uncoached students on the y-axis against precision ($1/\sqrt{\texttt{vi}}$) on the x-axis.  Back dots are for the math subtest and red dots for verbal subtest." width="672" />
<p class="caption">
Figure 9.1: Standardised mean difference in SAT scores between coached and uncoached students on the y-axis against precision (<span class="math inline">\(1/\sqrt{\texttt{vi}}\)</span>) on the x-axis. Back dots are for the math subtest and red dots for verbal subtest.
</p>
</div>
<p>Funnel plots are so called because the response shows high variance when precision is low (measurement error variance is high) and teh variance declines as sample sizes and precision increases. There are two flavours of meta-analysis: fixed-effect meta-analysis, which assumes that all of the variability between estimates is due to measurement error and random-effect meta-analysis, which assumes that estimates may also vary for other reasons (and usually that this variability does not depend on precision). In the context of the funnel plot, the fixed-effect meta-analysis assumes that at high precision all estimates converge on the same value whereas the random-effect meta-analysis allows some variability to exist. Both types of meta-analysis can be fitted in <span class="math inline">\(\texttt{MCMCglmm}\)</span>, although to me at least, the plausibility of the assumptions that underpin fixed-effect meta-analysis seem dubious. I usually start with random-effect meta-analyses which actually converges on the fixed-effect meta-analysis as the residual (<span class="math inline">\(\texttt{units}\)</span>) variance tends to zero.</p>
<p>There are multiple ways of setting up a (random-effect) meta-analysis in <span class="math inline">\(\texttt{MCMCglmm}\)</span> (see Section <a href="measurement.html#sec-meta-alternatives">9.3.2</a>). Here, I will go through the least intuitive method as it will provide the first step at understanding the next section. In Chapter <a href="cont-int.html#cont-int">6</a> we explored random regression and in Section <a href="cont-int.html#het-res">6.2</a> we saw that random regression models also impose assumptions about how the variances changes as function of the covariate. If a random slope model is fitted without random intercepts the variance across levels of the random effect is <span class="math inline">\(\sigma^2_ux^2\)</span> where <span class="math inline">\(x\)</span> is the covariate. Consequently, fitting an observation-level random regression model with the standard error (<span class="math inline">\(\texttt{sqrt(vi)}\)</span>) as <span class="math inline">\(x\)</span> and fixing <span class="math inline">\(\sigma^2_u\)</span> at one results in the variance being equal to the measurement error variance <span class="math inline">\(\texttt{vi}\)</span> as required. The model formula <code>idh(sqrt(vi)):units</code> fits such a model and the associated variance can be fixed at one in the prior.</p>
<div class="sourceCode" id="cb359"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb359-1"><a href="measurement.html#cb359-1" tabindex="-1"></a>prior.meta<span class="ot">&lt;-</span><span class="fu">list</span>(<span class="at">R=</span><span class="fu">IW</span>(<span class="dv">1</span>, <span class="fl">0.002</span>), <span class="at">G=</span><span class="fu">list</span>(<span class="at">G1=</span><span class="fu">list</span>(<span class="at">V=</span><span class="dv">1</span>, <span class="at">fix=</span><span class="dv">1</span>)))</span>
<span id="cb359-2"><a href="measurement.html#cb359-2" tabindex="-1"></a>m.meta<span class="ot">&lt;-</span><span class="fu">MCMCglmm</span>(yi<span class="sc">~</span>outcome, <span class="at">random=</span><span class="sc">~</span><span class="fu">idh</span>(<span class="fu">sqrt</span>(vi))<span class="sc">:</span>units, <span class="at">data=</span>dat.kalaian1996, <span class="at">prior=</span>prior.meta)</span>
<span id="cb359-3"><a href="measurement.html#cb359-3" tabindex="-1"></a><span class="fu">summary</span>(m.meta)</span></code></pre></div>
<pre><code>## 
##  Iterations = 3001:12991
##  Thinning interval  = 10
##  Sample size  = 1000 
## 
##  DIC: -185.792 
## 
##  G-structure:  ~idh(sqrt(vi)):units
## 
##                post.mean l-95% CI u-95% CI eff.samp
## sqrt(vi).units         1        1        1        0
## 
##  R-structure:  ~units
## 
##       post.mean  l-95% CI u-95% CI eff.samp
## units  0.002809 0.0002683 0.007807    254.9
## 
##  Location effects: yi ~ outcome 
## 
##               post.mean  l-95% CI  u-95% CI eff.samp  pMCMC    
## (Intercept)    0.129039  0.056073  0.206326      850 &lt;0.001 ***
## outcomeverbal -0.009728 -0.112622  0.088928     1000  0.862    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>We can see that the standardised difference is positive - for math, the scores of coached students are on average 0.13 standard deviations higher, and the impact of coaching does not seem to be tremendously different for the verbal subtest. The residual (<span class="math inline">\(\texttt{units}\)</span>) variance is small in comparison to the average measurement error variance (the average value of <span class="math inline">\(\texttt{vi}\)</span> (<span class="math inline">\(\bar{\texttt{vi}}\)</span>) is 0.081) - often this is expressed as <span class="math display">\[I^2=\sigma^2_{units}/(\sigma^2_{units}+\bar{\texttt{vi}})\]</span> the posterior mean of which is 0.033. In a fixed-effect meta-analysis, <span class="math inline">\(I^2=0\)</span>.</p>
<p>To the funnel plot in Figure <a href="measurement.html#fig:funnel">9.1</a> we can add the 95% prediction intervals for the difference in math scores (black) and verbal scores (red) (Figure <a href="measurement.html#fig:funnel2">9.2</a>).</p>
<div class="figure"><span style="display:block;" id="fig:funnel2"></span>
<img src="_bookdown_files/fig/funnel2-1.png" alt="Standardised mean difference in SAT scores between coached and uncoached students on the y-axis against precision ($1/\sqrt{\texttt{vi}}$) on the x-axis. Back dots are for the math subtest and red dots for verbal subtest. The solid horizontal lines are the predicted means and the dashed lines are the 95% prediction intervals obtained using a variance of $\sigma^2_\texttt{units}+\texttt{vi}$. The solid grey line is the 95% prediction interval for the math subtest assuming $\sigma^2_\texttt{units}=0$." width="672" />
<p class="caption">
Figure 9.2: Standardised mean difference in SAT scores between coached and uncoached students on the y-axis against precision (<span class="math inline">\(1/\sqrt{\texttt{vi}}\)</span>) on the x-axis. Back dots are for the math subtest and red dots for verbal subtest. The solid horizontal lines are the predicted means and the dashed lines are the 95% prediction intervals obtained using a variance of <span class="math inline">\(\sigma^2_\texttt{units}+\texttt{vi}\)</span>. The solid grey line is the 95% prediction interval for the math subtest assuming <span class="math inline">\(\sigma^2_\texttt{units}=0\)</span>.
</p>
</div>
<p>The 95% prediction intervals suggest a problem - the observations look less variable than predicted when precision is high. With only 67 observations it is hard to be sure whether this couldn’t be just due to chance, but it is tempting to suggest a problem exists because a random-effect meta-analysis was used and the estimate of <span class="math inline">\(\sigma^2_\texttt{units}\)</span> is somehow overestimated, perhaps because of an influential prior. However, the solid grey lines give the 95% prediction interval for the math subset (points in black) assuming <span class="math inline">\(\sigma^2_\texttt{units}=0\)</span> and the interval is almost unchanged. In my experience, this type of type of problem is relatively common in meta-analyses. For this reason, I often test, rather than assume, that the measurement error variance is exactly proportional to that stated - rather than fix <span class="math inline">\(\sigma^2_{u}\)</span> at one I allow it to be estimated.</p>
<div class="sourceCode" id="cb361"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb361-1"><a href="measurement.html#cb361-1" tabindex="-1"></a>prior.meta2<span class="ot">&lt;-</span><span class="fu">list</span>(<span class="at">R=</span><span class="fu">IW</span>(<span class="dv">1</span>, <span class="fl">0.002</span>), <span class="at">G=</span><span class="fu">F</span>(<span class="dv">1</span>,<span class="dv">1000</span>))</span>
<span id="cb361-2"><a href="measurement.html#cb361-2" tabindex="-1"></a>m.meta2<span class="ot">&lt;-</span><span class="fu">MCMCglmm</span>(yi<span class="sc">~</span>outcome, <span class="at">random=</span><span class="sc">~</span><span class="fu">idh</span>(<span class="fu">sqrt</span>(vi))<span class="sc">:</span>units, <span class="at">data=</span>dat.kalaian1996, <span class="at">prior=</span>prior.meta2)</span>
<span id="cb361-3"><a href="measurement.html#cb361-3" tabindex="-1"></a><span class="fu">summary</span>(m.meta2)</span></code></pre></div>
<pre><code>## 
##  Iterations = 3001:12991
##  Thinning interval  = 10
##  Sample size  = 1000 
## 
##  DIC: -181.3425 
## 
##  G-structure:  ~idh(sqrt(vi)):units
## 
##                post.mean l-95% CI u-95% CI eff.samp
## sqrt(vi).units    0.7733    0.481    1.099    490.2
## 
##  R-structure:  ~units
## 
##       post.mean  l-95% CI u-95% CI eff.samp
## units  0.003449 0.0001677  0.01008    267.4
## 
##  Location effects: yi ~ outcome 
## 
##               post.mean l-95% CI u-95% CI eff.samp  pMCMC    
## (Intercept)     0.12995  0.06866  0.20117     1000 &lt;0.001 ***
## outcomeverbal  -0.01122 -0.10607  0.07267     1000  0.846    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Although the best estimate suggests that the measurement error variance only scales with <span class="math inline">\(\texttt{vi}\)</span> by a factor 0.773 rather than one (as assumed in the more standard model), the credible intervals do overlap one and the improvement in the diagnostic prediction interval plot is only marginal (Figure <a href="measurement.html#fig:funnel3">9.3</a>).</p>
<div class="figure"><span style="display:block;" id="fig:funnel3"></span>
<img src="_bookdown_files/fig/funnel3-1.png" alt="Standardised mean difference in SAT scores between coached and uncoached students on the y-axis against precision ($1/\sqrt{\texttt{vi}}$) on the x-axis. Back dots are for the math subtest and red dots for verbal subtest. The solid horizontal lines are the predicted means and the dashed lines are the 95% prediction intervals obtained using a variance of $\sigma^2_\texttt{units}+\texttt{vi}$." width="672" />
<p class="caption">
Figure 9.3: Standardised mean difference in SAT scores between coached and uncoached students on the y-axis against precision (<span class="math inline">\(1/\sqrt{\texttt{vi}}\)</span>) on the x-axis. Back dots are for the math subtest and red dots for verbal subtest. The solid horizontal lines are the predicted means and the dashed lines are the 95% prediction intervals obtained using a variance of <span class="math inline">\(\sigma^2_\texttt{units}+\texttt{vi}\)</span>.
</p>
</div>
<div id="sec-meta-exact" class="section level3 hasAnchor" number="9.3.1">
<h3><span class="header-section-number">9.3.1</span> Exact meta-analysis<a href="measurement.html#sec-meta-exact" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Another possible source of model misspecification is the assumption that the measurement errors are normally distributed with a standard deviation equal to the standard error of the estimate. This is true for linear model coefficients, including the difference in the means for two groups, but only when the assumption of normality is met <em>and</em> the residual variance is known perfectly. In practice, the residual variance is not known exactly and is estimated from the data. The assumed measurement error distribution is then only approximate, although if the individual studies have moderate sample sizes (<span class="math inline">\(&gt;30\)</span>) the approximation is accurate enough that it is not worth worrying about. Given 59 of the 67 differences in <span class="math inline">\(\texttt{dat.kalaian1996}\)</span> were estimated from sample sizes in excess of 30, it seems unlikely that using a more accurate distribution for the measurement errors will dramatically change the model, but let’s try. Assuming the individual studies that contributed to <span class="math inline">\(\texttt{dat.kalaian1996}\)</span> were normally distributed, the distribution of the estimated difference follows a mean-shifted scaled t-distribution with a mean equal to the true difference, a scale equal to the reported standard error (<span class="math inline">\(\sqrt{\texttt{vi}}\)</span>) and degrees of freedom equal to the residual degrees of freedom. If we are prepared to assume no moderator variables were included when estimating the difference in the means the residual degrees of freedom will be equal to the sum of the sample sizes in each group minus two:</p>
<div class="sourceCode" id="cb363"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb363-1"><a href="measurement.html#cb363-1" tabindex="-1"></a>dat.kalaian1996<span class="sc">$</span>df<span class="ot">&lt;-</span>dat.kalaian1996<span class="sc">$</span>n1<span class="sc">+</span>dat.kalaian1996<span class="sc">$</span>n2<span class="dv">-2</span></span></code></pre></div>
<p>However, the differences in <span class="math inline">\(\texttt{dat.kalaian1996}\)</span> (<span class="math inline">\(\texttt{yi}\)</span>) are not raw differences, but have been standardised by the within group standard deviation. After standard-deviation standardisation the distribution of estimates is no longer a mean-shifted scaled t-distribution but a noncentral scaled t-distribution. The true (standardised) value is equal to the noncentrality parameter, and the scale and degrees of freedom are equal to the reported standard error and residual degrees of freedom from the model. When the true value is non-zero the distribution of errors will be asymmetric with a longer tail to the right when the true value is positive. When the true value is zero we have the standard scaled t-distribution which compared to the normal has longer tails. As the degrees of freedom increases the noncentral scaled t-distribution converges on the normal. <span class="math inline">\(\texttt{MCMCglmm}\)</span> allows the response to come from a noncentral scaled t-distribution (<code>family="ncst"</code>) if the scale and degrees of freedom are known and the linear model predicts the noncentrality parameter. When using <code>family="ncst"</code> three columns are expected: the estimate, it’s standard error and the residual degrees of freedom. Note that for such models, the meausrement errors are built into the distribution and do not need to be modelled using random effects:</p>
<div class="sourceCode" id="cb364"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb364-1"><a href="measurement.html#cb364-1" tabindex="-1"></a>m.meta3<span class="ot">&lt;-</span><span class="fu">MCMCglmm</span>(<span class="fu">cbind</span>(yi, <span class="fu">sqrt</span>(vi), df)<span class="sc">~</span>outcome, <span class="at">data=</span>dat.kalaian1996, <span class="at">prior=</span><span class="fu">list</span>(<span class="at">R=</span><span class="fu">list</span>(<span class="at">V=</span><span class="dv">1</span>, <span class="at">nu=</span><span class="fl">0.002</span>)), <span class="at">family=</span><span class="st">&quot;ncst&quot;</span>)</span>
<span id="cb364-2"><a href="measurement.html#cb364-2" tabindex="-1"></a><span class="fu">summary</span>(m.meta3)</span></code></pre></div>
<pre><code>## 
##  Iterations = 3001:12991
##  Thinning interval  = 10
##  Sample size  = 1000 
## 
##  DIC: -8.503967 
## 
##  R-structure:  ~units
## 
##       post.mean  l-95% CI u-95% CI eff.samp
## units   0.00219 0.0001578 0.006151    121.1
## 
##  Location effects: cbind(yi, sqrt(vi), df) ~ outcome 
## 
##               post.mean  l-95% CI  u-95% CI eff.samp  pMCMC    
## (Intercept)    0.128878  0.057199  0.195495    85.04 &lt;0.001 ***
## outcomeverbal -0.007312 -0.094338  0.094081    77.52    0.9    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The posterior distributions of the parameters are almost identical to those seen with the standard model (<code>m.meta</code>), as expected given the high sample sizes. Obtaining the prediction intervals is a little tricky with respect to the precision is a little tricky, since for a given precision the residual degrees of freedom might vary. Moreover the response is now assumed to be the sum of a normally distributed <span class="math inline">\(\textttt{unit}\)</span> effect and a noncentral scaled <span class="math inline">\(t\)</span> effect and so the quantiles of the distribution are unknown. We can of course obtain posterior predictive intervals for our observed data and overly them, and as expected it is very similar to Figure <a href="measurement.html#fig:funnel2">9.2</a>.</p>
<div class="figure"><span style="display:block;" id="fig:funnel4"></span>
<img src="_bookdown_files/fig/funnel4-1.png" alt="Standardised mean difference in SAT scores between coached and uncoached students on the y-axis against precision ($1/\sqrt{\texttt{vi}}$) on the x-axis. Back dots are for the math subtest and red dots for verbal subtest. The solid horizontal lines are the predicted means and the dashed lines are the 95% prediction intervals obtained assuming the response follows a noncentral scaled t-distribution." width="672" />
<p class="caption">
Figure 9.4: Standardised mean difference in SAT scores between coached and uncoached students on the y-axis against precision (<span class="math inline">\(1/\sqrt{\texttt{vi}}\)</span>) on the x-axis. Back dots are for the math subtest and red dots for verbal subtest. The solid horizontal lines are the predicted means and the dashed lines are the 95% prediction intervals obtained assuming the response follows a noncentral scaled t-distribution.
</p>
</div>
<p>It is always a little annoying when standardised values are published without the accompanying raw values or the values used to standardise. Particularly so, when the case for standardisation seems to be misplaced: I bet coaching companies don’t have statements on their websites saying they raise SAT grades by <span class="math inline">\(x\)</span> standard deviations - they will say they raise them by <span class="math inline">\(x\)</span> points (a raw difference) or by <span class="math inline">\(x\)</span> percent (a mean standardised difference). If raw differences and their standard errors had been reported an exact meta-analysis on the raw differences could have been performed by specifying the response to be a mean-shifted scaled t-distribution ( <code>family = "msst"</code>). As with the noncentral scaled <span class="math inline">\(t\)</span>-distribution, three columns are expected: the estimate followed by its standard error and the residual degrees of freedom.</p>
</div>
<div id="sec-meta-alternatives" class="section level3 hasAnchor" number="9.3.2">
<h3><span class="header-section-number">9.3.2</span> <span class="math inline">\(\texttt{mev}\)</span>, <span class="math inline">\(\texttt{units}\)</span> structure and <span class="math inline">\(\texttt{ginverse}\)</span><a href="measurement.html#sec-meta-alternatives" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>When fitting a standard meta-analysis (<span class="math inline">\(\texttt{m.meta}\)</span>) we set the problem up as a random regression using <span class="math inline">\(\texttt{idh(sqrt(vi)):units}\)</span> and fixed the corresponding variance at one. There are at least three other ways to achieve the same goal.</p>
<p><span class="math inline">\({\bf \texttt{mev}}\)</span>: The argument in $ takes a vector of measurement error variances</p>
<div class="sourceCode" id="cb366"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb366-1"><a href="measurement.html#cb366-1" tabindex="-1"></a>m.mev<span class="ot">&lt;-</span><span class="fu">MCMCglmm</span>(yi<span class="sc">~</span>outcome, <span class="at">data=</span>dat.kalaian1996, <span class="at">mev=</span>dat.kalaian1996<span class="sc">$</span>vi, <span class="at">prior=</span><span class="fu">list</span>(<span class="at">R=</span><span class="fu">IW</span>(<span class="dv">1</span>, <span class="fl">0.002</span>)))</span></code></pre></div>
<p><span class="math inline">\({\bf \texttt{units} \textrm{structure}}\)</span>: A <span class="math inline">\(\texttt{units}\)</span> by <span class="math inline">\(\texttt{units}\)</span> measurement error covariance matrix can be specified in the random formula and then fixed in the prior. In standard meta-analysis the measurement errors on different observations are uncorrelated and so the covariance matrix is diagonal and can be fitted using an <span class="math inline">\(\texttt{idh}\)</span> structure. While this is much more computationally efficient than fitting an equivalent <span class="math inline">\(\texttt{us}\)</span> structure, it may still be slow if the data set is large:</p>
<div class="sourceCode" id="cb367"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb367-1"><a href="measurement.html#cb367-1" tabindex="-1"></a>prior.units<span class="ot">&lt;-</span><span class="fu">list</span>(<span class="at">R=</span><span class="fu">IW</span>(<span class="dv">1</span>, <span class="fl">0.002</span>), <span class="at">G=</span><span class="fu">list</span>(<span class="at">G1=</span><span class="fu">list</span>(<span class="at">V=</span><span class="fu">diag</span>(dat.kalaian1996<span class="sc">$</span>vi), <span class="at">fix=</span><span class="dv">1</span>)))</span>
<span id="cb367-2"><a href="measurement.html#cb367-2" tabindex="-1"></a>m.idh<span class="ot">&lt;-</span><span class="fu">MCMCglmm</span>(yi<span class="sc">~</span>outcome, <span class="at">random=</span><span class="sc">~</span><span class="fu">idh</span>(units)<span class="sc">:</span>units, <span class="at">data=</span>dat.kalaian1996, <span class="at">prior=</span>prior.units)</span></code></pre></div>
<p><span class="math inline">\({\bf \texttt{ginverse}}\)</span>: A <span class="math inline">\(\texttt{units}\)</span> by <span class="math inline">\(\texttt{units}\)</span> measurement error covariance matrix can be specified through the <span class="math inline">\(\texttt{ginverse}\)</span> argument to <span class="math inline">\(\texttt{MCMCglmm}\)</span>. Conceptually this is equivalent to the specification above, but computationally more efficient.</p>
<div class="sourceCode" id="cb368"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb368-1"><a href="measurement.html#cb368-1" tabindex="-1"></a>ivi<span class="ot">&lt;-</span><span class="fu">as</span>(<span class="fu">Diagonal</span>(<span class="fu">nrow</span>(dat.kalaian1996), <span class="dv">1</span><span class="sc">/</span>dat.kalaian1996<span class="sc">$</span>vi), <span class="st">&quot;CsparseMatrix&quot;</span>)</span>
<span id="cb368-2"><a href="measurement.html#cb368-2" tabindex="-1"></a><span class="fu">rownames</span>(ivi)<span class="ot">&lt;-</span>dat.kalaian1996<span class="sc">$</span>id</span>
<span id="cb368-3"><a href="measurement.html#cb368-3" tabindex="-1"></a></span>
<span id="cb368-4"><a href="measurement.html#cb368-4" tabindex="-1"></a>prior.ginv<span class="ot">&lt;-</span><span class="fu">list</span>(<span class="at">R=</span><span class="fu">IW</span>(<span class="dv">1</span>, <span class="fl">0.002</span>), <span class="at">G=</span><span class="fu">list</span>(<span class="at">G1=</span><span class="fu">list</span>(<span class="at">V=</span><span class="dv">1</span>, <span class="at">fix=</span><span class="dv">1</span>)))</span>
<span id="cb368-5"><a href="measurement.html#cb368-5" tabindex="-1"></a></span>
<span id="cb368-6"><a href="measurement.html#cb368-6" tabindex="-1"></a>m.ginv<span class="ot">&lt;-</span><span class="fu">MCMCglmm</span>(yi<span class="sc">~</span>outcome, <span class="at">random=</span><span class="sc">~</span>id, <span class="at">data=</span>dat.kalaian1996, <span class="at">prior=</span>prior.ginv, <span class="at">ginverse=</span><span class="fu">list</span>(<span class="at">id=</span>ivi))</span></code></pre></div>
<p>All of the above models are equivalent to the first model used (<span class="math inline">\(\texttt{m.meta}\)</span>).</p>
<div class="sourceCode" id="cb369"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb369-1"><a href="measurement.html#cb369-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">mcmc.list</span>(m.meta<span class="sc">$</span>Sol, m.mev<span class="sc">$</span>Sol, m.idh<span class="sc">$</span>Sol, m.ginv<span class="sc">$</span>Sol))</span></code></pre></div>
<p><img src="_bookdown_files/fig/unnamed-chunk-199-1.png" alt="" width="672" /></p>
</div>
<div id="multivariate-meta-analysis" class="section level3 hasAnchor" number="9.3.3">
<h3><span class="header-section-number">9.3.3</span> Multivariate meta-analysis<a href="measurement.html#multivariate-meta-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In some cases measurement errors may be correlated across observations. For example, in <span class="math inline">\(\texttt{dat.kalaian1996}\)</span>, 20 studies contributed two differences, one for verbal and one for math subtests. The pair of differences were calculated from data on the same set of students and so we might expect their estimation error to be correlated - for example, if the coached students for a particular study happened to be intrinsically poor students we might expect the two differences to be smaller than their expectation. In some cases, we might know the measurement error correlation between observations (for example, if we were to analyses pairs of coefficients obtained from linear models) but often - as here - we do not. The help file for <span class="math inline">\(\texttt{dat.kalaian1996}\)</span> performs an analysis where the measurement error correlation between observations from the same study is assumed to be 0.66. We can impose this assumption in a <span class="math inline">\(\texttt{MCMCglmm}\)</span> model by forming the inverse measurement error covariance matrix as we did in the previous section. Formatting the matrix is a bit painful and so I’ll hide the details</p>
<details>
<summary>
here
</summary>
<div class="sourceCode" id="cb370"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb370-1"><a href="measurement.html#cb370-1" tabindex="-1"></a>inverse.cor<span class="ot">&lt;-</span><span class="cf">function</span>(v, r){</span>
<span id="cb370-2"><a href="measurement.html#cb370-2" tabindex="-1"></a></span>
<span id="cb370-3"><a href="measurement.html#cb370-3" tabindex="-1"></a>    R<span class="ot">&lt;-</span><span class="fu">matrix</span>(r, <span class="fu">length</span>(v), <span class="fu">length</span>(v))</span>
<span id="cb370-4"><a href="measurement.html#cb370-4" tabindex="-1"></a>    <span class="fu">diag</span>(R)<span class="ot">&lt;-</span><span class="dv">1</span></span>
<span id="cb370-5"><a href="measurement.html#cb370-5" tabindex="-1"></a>    <span class="co"># create the correlation matrix</span></span>
<span id="cb370-6"><a href="measurement.html#cb370-6" tabindex="-1"></a></span>
<span id="cb370-7"><a href="measurement.html#cb370-7" tabindex="-1"></a>    V<span class="ot">&lt;-</span><span class="fu">crossprod</span>(<span class="fu">t</span>(<span class="fu">sqrt</span>(v)))</span>
<span id="cb370-8"><a href="measurement.html#cb370-8" tabindex="-1"></a>    <span class="co"># create the covariance matrix had r been 1.</span></span>
<span id="cb370-9"><a href="measurement.html#cb370-9" tabindex="-1"></a></span>
<span id="cb370-10"><a href="measurement.html#cb370-10" tabindex="-1"></a>    <span class="fu">return</span>(<span class="fu">solve</span>(V<span class="sc">*</span>R))</span>
<span id="cb370-11"><a href="measurement.html#cb370-11" tabindex="-1"></a>} </span>
<span id="cb370-12"><a href="measurement.html#cb370-12" tabindex="-1"></a><span class="co"># a function for creating an inverse covariance matrix given the variances (v) and a constant correlation (r) </span></span>
<span id="cb370-13"><a href="measurement.html#cb370-13" tabindex="-1"></a></span>
<span id="cb370-14"><a href="measurement.html#cb370-14" tabindex="-1"></a>ivi<span class="ot">&lt;-</span><span class="fu">tapply</span>(dat.kalaian1996<span class="sc">$</span>vi, dat.kalaian1996<span class="sc">$</span>study, inverse.cor, <span class="at">r=</span><span class="fl">0.66</span>)</span>
<span id="cb370-15"><a href="measurement.html#cb370-15" tabindex="-1"></a><span class="co"># for each study create the inverse measurement error covariance matrix</span></span>
<span id="cb370-16"><a href="measurement.html#cb370-16" tabindex="-1"></a></span>
<span id="cb370-17"><a href="measurement.html#cb370-17" tabindex="-1"></a>ivi<span class="ot">&lt;-</span><span class="fu">bdiag</span>(ivi)</span>
<span id="cb370-18"><a href="measurement.html#cb370-18" tabindex="-1"></a><span class="co"># turn the list of matrices into a sparse block diagonal</span></span>
<span id="cb370-19"><a href="measurement.html#cb370-19" tabindex="-1"></a></span>
<span id="cb370-20"><a href="measurement.html#cb370-20" tabindex="-1"></a>idx.after.sort <span class="ot">&lt;-</span> <span class="fu">order</span>(dat.kalaian1996<span class="sc">$</span>study, <span class="fu">seq_along</span>(dat.kalaian1996<span class="sc">$</span>study))</span>
<span id="cb370-21"><a href="measurement.html#cb370-21" tabindex="-1"></a><span class="co"># for situations where observations aren&#39;t ordered (within studies in this example)</span></span>
<span id="cb370-22"><a href="measurement.html#cb370-22" tabindex="-1"></a><span class="co"># need to make sure rows/columns of ivi correspond to the correct obseravtions</span></span>
<span id="cb370-23"><a href="measurement.html#cb370-23" tabindex="-1"></a></span>
<span id="cb370-24"><a href="measurement.html#cb370-24" tabindex="-1"></a><span class="fu">rownames</span>(ivi)<span class="ot">&lt;-</span>dat.kalaian1996<span class="sc">$</span>id[idx.after.sort]</span></code></pre></div>
</details>
<p><br>
but it is instructive to look at the output. For example, if we look at row/columns 60 to 63 of the inverse (stored as <span class="math inline">\(\texttt{ivi}\)</span>) we get</p>
<div class="sourceCode" id="cb371"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb371-1"><a href="measurement.html#cb371-1" tabindex="-1"></a>ivi[<span class="fu">c</span>(<span class="dv">60</span><span class="sc">:</span><span class="dv">63</span>), <span class="fu">c</span>(<span class="dv">60</span><span class="sc">:</span><span class="dv">63</span>)]</span></code></pre></div>
<pre><code>## 4 x 4 sparse Matrix of class &quot;dsCMatrix&quot;
##          29       65        41        42
## 29 7.674597 .          .         .      
## 65 .        5.885815   .         .      
## 41 .        .         46.02060 -29.76147
## 42 .        .        -29.76147  44.18437</code></pre>
<p>This matrix corresponds to observations with <span class="math inline">\(\texttt{id}\)</span>’s 29, 65, 41 and 42:</p>
<div class="sourceCode" id="cb373"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb373-1"><a href="measurement.html#cb373-1" tabindex="-1"></a>dat.kalaian1996[<span class="fu">match</span>(<span class="fu">rownames</span>(ivi)[<span class="dv">60</span><span class="sc">:</span><span class="dv">63</span>], dat.kalaian1996<span class="sc">$</span>id),<span class="fu">c</span>(<span class="st">&quot;id&quot;</span>, <span class="st">&quot;study&quot;</span>, <span class="st">&quot;vi&quot;</span>)]</span></code></pre></div>
<pre><code>##    id                   study     vi
## 29 29 Roberts &amp; Oppenheim (N) 0.1303
## 65 65                  Teague 0.1699
## 41 41                  Whitla 0.0385
## 42 42                  Whitla 0.0401</code></pre>
<p>The first two studies only contributed one observation and so their rows/columns only have a diagonal element equal to 1/<span class="math inline">\(\texttt{vi}\)</span>. The final two observations are from the same study and so the inverse has a non-zero element in the off-diagonal. As in the previous section we can simply fit this as a ginverse with the associated variance fixed at one:</p>
<div class="sourceCode" id="cb375"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb375-1"><a href="measurement.html#cb375-1" tabindex="-1"></a>prior.meta3<span class="ot">&lt;-</span><span class="fu">list</span>(<span class="at">R=</span><span class="fu">IW</span>(<span class="dv">1</span>, <span class="fl">0.002</span>), <span class="at">G=</span><span class="fu">list</span>(<span class="at">G1=</span><span class="fu">list</span>(<span class="at">V=</span><span class="dv">1</span>, <span class="at">fix=</span><span class="dv">1</span>)))</span>
<span id="cb375-2"><a href="measurement.html#cb375-2" tabindex="-1"></a>m.meta3<span class="ot">&lt;-</span><span class="fu">MCMCglmm</span>(yi<span class="sc">~</span>outcome, <span class="at">random=</span><span class="sc">~</span>id, <span class="at">data=</span>dat.kalaian1996, <span class="at">ginverse=</span><span class="fu">list</span>(<span class="at">id=</span>ivi), <span class="at">prior=</span>prior.meta3)</span>
<span id="cb375-3"><a href="measurement.html#cb375-3" tabindex="-1"></a><span class="fu">summary</span>(m.meta3)</span></code></pre></div>
<pre><code>## 
##  Iterations = 3001:12991
##  Thinning interval  = 10
##  Sample size  = 1000 
## 
##  DIC: -107.6008 
## 
##  G-structure:  ~id
## 
##    post.mean l-95% CI u-95% CI eff.samp
## id         1        1        1        0
## 
##  R-structure:  ~units
## 
##       post.mean  l-95% CI u-95% CI eff.samp
## units  0.007692 0.0006589  0.01684    278.3
## 
##  Location effects: yi ~ outcome 
## 
##               post.mean l-95% CI u-95% CI eff.samp  pMCMC    
## (Intercept)     0.13684  0.05972  0.21299     1000 &lt;0.001 ***
## outcomeverbal  -0.01841 -0.10029  0.06581     1000  0.626    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>An equivalent way to fit this model is to allow the pair of random slopes from our standard model to be correlated when they come from the same study, and fix the correlation at 0.66<a href="#fn45" class="footnote-ref" id="fnref45"><sup>45</sup></a>:</p>
<div class="sourceCode" id="cb377"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb377-1"><a href="measurement.html#cb377-1" tabindex="-1"></a>V<span class="ot">&lt;-</span><span class="fu">matrix</span>(<span class="fl">0.66</span>, <span class="dv">2</span>, <span class="dv">2</span>)</span>
<span id="cb377-2"><a href="measurement.html#cb377-2" tabindex="-1"></a><span class="fu">diag</span>(V)<span class="ot">&lt;-</span><span class="dv">1</span></span>
<span id="cb377-3"><a href="measurement.html#cb377-3" tabindex="-1"></a></span>
<span id="cb377-4"><a href="measurement.html#cb377-4" tabindex="-1"></a>prior.meta4<span class="ot">&lt;-</span><span class="fu">list</span>(<span class="at">R=</span><span class="fu">IW</span>(<span class="dv">1</span>, <span class="fl">0.002</span>), <span class="at">G=</span><span class="fu">list</span>(<span class="at">G1=</span><span class="fu">list</span>(<span class="at">V=</span>V, <span class="at">fix=</span><span class="dv">1</span>)))</span>
<span id="cb377-5"><a href="measurement.html#cb377-5" tabindex="-1"></a>m.meta4<span class="ot">&lt;-</span><span class="fu">MCMCglmm</span>(yi<span class="sc">~</span>outcome, <span class="at">random=</span><span class="sc">~</span><span class="fu">us</span>(outcome<span class="sc">:</span><span class="fu">sqrt</span>(vi))<span class="sc">:</span>study, <span class="at">data=</span>dat.kalaian1996, <span class="at">prior=</span>prior.meta4)</span>
<span id="cb377-6"><a href="measurement.html#cb377-6" tabindex="-1"></a><span class="fu">summary</span>(m.meta4)</span></code></pre></div>
<pre><code>## 
##  Iterations = 3001:12991
##  Thinning interval  = 10
##  Sample size  = 1000 
## 
##  DIC: -108.0545 
## 
##  G-structure:  ~us(outcome:sqrt(vi)):study
## 
##                                                     post.mean l-95% CI u-95% CI
## outcomemath:sqrt(vi):outcomemath:sqrt(vi).study          1.00     1.00     1.00
## outcomeverbal:sqrt(vi):outcomemath:sqrt(vi).study        0.66     0.66     0.66
## outcomemath:sqrt(vi):outcomeverbal:sqrt(vi).study        0.66     0.66     0.66
## outcomeverbal:sqrt(vi):outcomeverbal:sqrt(vi).study      1.00     1.00     1.00
##                                                     eff.samp
## outcomemath:sqrt(vi):outcomemath:sqrt(vi).study            0
## outcomeverbal:sqrt(vi):outcomemath:sqrt(vi).study          0
## outcomemath:sqrt(vi):outcomeverbal:sqrt(vi).study          0
## outcomeverbal:sqrt(vi):outcomeverbal:sqrt(vi).study        0
## 
##  R-structure:  ~units
## 
##       post.mean  l-95% CI u-95% CI eff.samp
## units  0.007759 0.0007515  0.01771    418.2
## 
##  Location effects: yi ~ outcome 
## 
##               post.mean l-95% CI u-95% CI eff.samp  pMCMC    
## (Intercept)     0.13831  0.05480  0.21404     1000 &lt;0.001 ***
## outcomeverbal  -0.02001 -0.10931  0.05660     1000   0.64    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>It’s not clear where the value 0.66 comes from, and in fact rather than fixing the correlation to be 0.66 we could try to estimate it. This can be achieved by replacing the <span class="math inline">\(\texttt{us}\)</span> variance structure with a <span class="math inline">\(\texttt{corg}\)</span> variance structure. This fixes the diagonal elements of the covariance matrix to one, but allows the correlation to be estimated. For a <span class="math inline">\(2\times 2\)</span> correlation matrix, specifying the off-diagonal elements of $ to be zero and having <span class="math inline">\(\texttt{nu=1}\)</span> results in a flat prior for the correlation (Section <a href="cat-int.html#VCVprior-r-sec">5.3.2</a>).</p>
<div class="sourceCode" id="cb379"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb379-1"><a href="measurement.html#cb379-1" tabindex="-1"></a>prior.meta5<span class="ot">&lt;-</span><span class="fu">list</span>(<span class="at">R=</span><span class="fu">IW</span>(<span class="dv">1</span>, <span class="fl">0.002</span>), <span class="at">G=</span><span class="fu">list</span>(<span class="at">G1=</span><span class="fu">list</span>(<span class="at">V=</span><span class="fu">diag</span>(<span class="dv">2</span>), <span class="at">nu=</span><span class="dv">1</span>)))</span>
<span id="cb379-2"><a href="measurement.html#cb379-2" tabindex="-1"></a>m.meta5<span class="ot">&lt;-</span><span class="fu">MCMCglmm</span>(yi<span class="sc">~</span>outcome, <span class="at">random=</span><span class="sc">~</span><span class="fu">corg</span>(outcome<span class="sc">:</span><span class="fu">sqrt</span>(vi))<span class="sc">:</span>study, <span class="at">data=</span>dat.kalaian1996, <span class="at">prior=</span>prior.meta5)</span>
<span id="cb379-3"><a href="measurement.html#cb379-3" tabindex="-1"></a><span class="fu">summary</span>(m.meta5)</span></code></pre></div>
<pre><code>## 
##  Iterations = 3001:12991
##  Thinning interval  = 10
##  Sample size  = 1000 
## 
##  DIC: -182.0488 
## 
##  G-structure:  ~corg(outcome:sqrt(vi)):study
## 
##                                                     post.mean l-95% CI u-95% CI
## outcomemath:sqrt(vi):outcomemath:sqrt(vi).study        1.0000   1.0000   1.0000
## outcomeverbal:sqrt(vi):outcomemath:sqrt(vi).study      0.1056  -0.3279   0.5128
## outcomemath:sqrt(vi):outcomeverbal:sqrt(vi).study      0.1056  -0.3279   0.5128
## outcomeverbal:sqrt(vi):outcomeverbal:sqrt(vi).study    1.0000   1.0000   1.0000
##                                                     eff.samp
## outcomemath:sqrt(vi):outcomemath:sqrt(vi).study            0
## outcomeverbal:sqrt(vi):outcomemath:sqrt(vi).study       1000
## outcomemath:sqrt(vi):outcomeverbal:sqrt(vi).study       1000
## outcomeverbal:sqrt(vi):outcomeverbal:sqrt(vi).study        0
## 
##  R-structure:  ~units
## 
##       post.mean  l-95% CI u-95% CI eff.samp
## units  0.003067 0.0001518 0.008255    279.1
## 
##  Location effects: yi ~ outcome 
## 
##               post.mean  l-95% CI  u-95% CI eff.samp  pMCMC    
## (Intercept)    0.129378  0.059329  0.197668     1000 &lt;0.001 ***
## outcomeverbal -0.009422 -0.100556  0.089569     1000  0.836    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The credible intervals on the correlation are very wide (-0.328 – 0.513) but it does seem like the value of 0.66 assumed in model <span class="math inline">\(\texttt{m.meta4}\)</span> is unjustifiably high.</p>
</div>
</div>
<div id="interval-data" class="section level2 hasAnchor" number="9.4">
<h2><span class="header-section-number">9.4</span> Interval Data<a href="measurement.html#interval-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In the meta-analyses covered in Section <a href="measurement.html#meta-sec">9.3</a> we worked with the measurement error variance associated with an estimate. If only confidence/credible intervals are given for an estimate, it is possible to obtain the measurement error variance assuming a distribution for the errors. For example, if the distribution is normal and the lower and upper interval are <span class="math inline">\(l\)</span> and <span class="math inline">\(u\)</span> respectively, then the estimate would be the midpoint <span class="math inline">\(y=(l+u)/2\)</span> and the measurement error standard deviation would be</p>
<p><span class="math display">\[\sigma_m = \frac{u-l}{2Q(1-\alpha/2)}\]</span></p>
<p>where <span class="math inline">\(Q\)</span> is the quantile function of the unit normal (<span class="math inline">\(\texttt{qnorm}\)</span>) and <span class="math inline">\(\alpha\)</span> is one minus the confidence level (e.g. 0.05 for 95% confidence intervals).</p>
<p>In some cases, intervals are given but without the corresponding confidence level. For example, in <span class="citation">(<a href="#ref-Phillimore.2016"><strong>Phillimore.2016?</strong></a>)</span> we analysed citizen-science data on when birds lay their eggs. Exact dates are not known and only an interval is given. The standard way of treating such data is to treat them as censored. Censoring assumes that before model building, the probability density for the true value is flat across the interval. However, for the laying date data quite a lot of information goes into calculating the interval such that the true value is more likely to be close to the centre of the interval. In addition, the intervals are calculated in the hope they are comparable between observations - two observations may have very different interval lengths, but it is still hoped that the probability the true value lies inside the interval is the same in both cases. In such cases, <span class="math inline">\(\alpha\)</span> and therefore <span class="math inline">\(2Q(1-\alpha/2)\)</span> is constant. In Section <a href="measurement.html#meta-sec">9.3</a> we fitted a model (<span class="math inline">\(\texttt{m.meta2}\)</span>) which allowed the measurement error variance to be proportional to, rather than exactly equal to, the reported measurement error variance (<span class="math inline">\(\texttt{vi}\)</span>). The constant of proportionality could be estimated since <span class="math inline">\(\texttt{vi}\)</span> varied and the empirical change in variance with <span class="math inline">\(\texttt{vi}\)</span> could be assessed. Analysing interval data<a href="#fn46" class="footnote-ref" id="fnref46"><sup>46</sup></a> is essentially the same problem: we can treat <span class="math inline">\(y\)</span> as the observation and <span class="math inline">\((l-u)^2\)</span> as <span class="math inline">\(\texttt{vi}\)</span>. The estimate of the constant of proportionality, <span class="math inline">\(c\)</span>, is then equal to <span class="math inline">\((1/2Q(1-\alpha/2))^{2}\)</span> and so we can obtain an estimate of the unknown confidence interval as <span class="math inline">\(1-\alpha = 2F(1/2\sqrt{c})-1\)</span>, where <span class="math inline">\(F\)</span> is the cumulative distribution function of the unit normal (<span class="math inline">\(\texttt{pnorm}\)</span>).</p>
<p>For we can obtain the 95% (<span class="math inline">\(\alpha=0.05\)</span>) confidence intervals from <span class="math inline">\(\texttt{vi}\)</span>:</p>
<div class="sourceCode" id="cb381"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb381-1"><a href="measurement.html#cb381-1" tabindex="-1"></a>dat.kalaian1996<span class="sc">$</span>l<span class="ot">&lt;-</span><span class="fu">qnorm</span>(<span class="fl">0.025</span>, dat.kalaian1996<span class="sc">$</span>yi, <span class="fu">sqrt</span>(dat.kalaian1996<span class="sc">$</span>vi))</span>
<span id="cb381-2"><a href="measurement.html#cb381-2" tabindex="-1"></a>dat.kalaian1996<span class="sc">$</span>u<span class="ot">&lt;-</span><span class="fu">qnorm</span>(<span class="fl">0.975</span>, dat.kalaian1996<span class="sc">$</span>yi, <span class="fu">sqrt</span>(dat.kalaian1996<span class="sc">$</span>vi))</span></code></pre></div>
<div class="sourceCode" id="cb382"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb382-1"><a href="measurement.html#cb382-1" tabindex="-1"></a>prior.meta6<span class="ot">&lt;-</span><span class="fu">list</span>(<span class="at">R=</span><span class="fu">IW</span>(<span class="dv">1</span>, <span class="fl">0.002</span>), <span class="at">G=</span><span class="fu">F</span>(<span class="dv">1</span>,<span class="dv">1000</span>))</span>
<span id="cb382-2"><a href="measurement.html#cb382-2" tabindex="-1"></a>m.meta6<span class="ot">&lt;-</span><span class="fu">MCMCglmm</span>(yi<span class="sc">~</span>outcome, <span class="at">random=</span><span class="sc">~</span><span class="fu">idh</span>(<span class="fu">I</span>(u<span class="sc">-</span>l))<span class="sc">:</span>units, <span class="at">data=</span>dat.kalaian1996, <span class="at">prior=</span>prior.meta2)</span>
<span id="cb382-3"><a href="measurement.html#cb382-3" tabindex="-1"></a><span class="fu">summary</span>(m.meta6)</span></code></pre></div>
<pre><code>## 
##  Iterations = 3001:12991
##  Thinning interval  = 10
##  Sample size  = 1000 
## 
##  DIC: -181.8545 
## 
##  G-structure:  ~idh(I(u - l)):units
## 
##                post.mean l-95% CI u-95% CI eff.samp
## I(u - l).units   0.04933  0.02968  0.06946    502.1
## 
##  R-structure:  ~units
## 
##       post.mean  l-95% CI u-95% CI eff.samp
## units  0.003973 0.0002097  0.01247    210.2
## 
##  Location effects: yi ~ outcome 
## 
##               post.mean l-95% CI u-95% CI eff.samp  pMCMC    
## (Intercept)     0.13005  0.06348  0.20410     1000 &lt;0.001 ***
## outcomeverbal  -0.01292 -0.10285  0.08485     1000  0.788    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Given an <span class="math inline">\(\alpha\)</span> of 0.05 we expect the estimated variance to be $(1/2Q(1-/2))^{2}=0.065 and we can see the best estimate is lower than this although the credible intervals overlap 0.065. The best estimate of the confidence level can also be obtained:</p>
<div class="sourceCode" id="cb384"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb384-1"><a href="measurement.html#cb384-1" tabindex="-1"></a>c<span class="ot">&lt;-</span>m.meta6<span class="sc">$</span>VCV[,<span class="st">&quot;I(u - l).units&quot;</span>]</span>
<span id="cb384-2"><a href="measurement.html#cb384-2" tabindex="-1"></a>ci<span class="ot">&lt;-</span><span class="dv">2</span><span class="sc">*</span><span class="fu">pnorm</span>(<span class="dv">1</span><span class="sc">/</span>(<span class="dv">2</span><span class="sc">*</span><span class="fu">sqrt</span>(c)))<span class="sc">-</span><span class="dv">1</span></span>
<span id="cb384-3"><a href="measurement.html#cb384-3" tabindex="-1"></a><span class="fu">plot</span>(ci)</span></code></pre></div>
<p><img src="_bookdown_files/fig/unnamed-chunk-208-1.png" alt="" width="672" /></p>
<p>and we can see that 0.95 has some support but much of the posterior density is above this and the posterior mean is 0.974. As we saw from model <span class="math inline">\(\texttt{m.meta2}\)</span>, the best estimate is that the measurement error variance scales by a factor 0.773 with the reported measurement error variance, <span class="math inline">\(\texttt{vi}\)</span>. Since the reported measurement error variance may be inflated the assumed confidence level may have been deflated and the actual level may exceed 95%.</p>
</div>
<div id="error-in-the-predictors" class="section level2 hasAnchor" number="9.5">
<h2><span class="header-section-number">9.5</span> Error in the predictors<a href="measurement.html#error-in-the-predictors" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Since the object of an analysis is to model the response, accommodating missing values or error in the response is relatively straightforward - we’ve already done the hard work of thinking about how the response may be distributed. On the other hand, we generally condition on the predictor variables in a GLMM and while we must consider how the response depends on them, we do not need to consider their distribution. However, when we need to accommodating missing values or error in predictor variables we have little option but to consider how their true values and errors might be distributed. We can do this formally by fitting a multi-response variable where the would-be predictor is treated as a response variable and a shared parameter exists that links the predictor variable with the target response variable. However, this is only really feasible when we have one or few such predictor variables. Alternatively, we can use more heuristic approaches that impute true values using an approximate distribution. Before addressing each in turn it will be necessary to draw a distinction between two types of error - classical and Berkson.</p>
<div id="classical-and-berkson-errors." class="section level3 hasAnchor" number="9.5.1">
<h3><span class="header-section-number">9.5.1</span> Classical and Berkson errors.<a href="measurement.html#classical-and-berkson-errors." class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To understand the distinction between classical and Berkson errors, imagine a predictor variable <span class="math inline">\(x\)</span> for which we can only observe <span class="math inline">\(\hat{x}\)</span>. With classical errors, <span class="math inline">\(\hat{x}\)</span> is distributed around <span class="math inline">\(x\)</span> with some error: <span class="math inline">\(\hat{x} = x+e_c\)</span>. With Berkson errors, <span class="math inline">\(x\)</span> is distributed around <span class="math inline">\(\hat{x}\)</span> with some deviation: <span class="math inline">\(x = \hat{x}+e_b\)</span>. The subtle difference between the two types of error is best understood in terms of an example. Imagine, I wanted to assess the impact of smoking on health and so I recruit two groups of patients. Patients in Group A smoke ten ten cigarettes a day and patients in Group B smoke twenty cigarettes a day. However, rather than using 10 and 20 as my predictor values, I use the number of cigarettes each patient tells me they smoked, and they have fallible memories. Here we have classical errors: the true value (<span class="math inline">\(x\)</span>) is either 10 or 20 but my observed values (<span class="math inline">\({\hat x}\)</span>) vary around this due to bad memory: <span class="math inline">\(Var({\hat x})&gt;Var(x)\)</span>. Another possibility is that I <em>tell</em> patients in Group A to smoke ten ten cigarettes a day and patients in Group B to smoke twenty cigarettes a day. However, although patients in the two groups <em>on average</em> smoke 10 or 20 cigarettes each patient may smoke slightly more or less than the average. However, I am not party to this information and the true number of cigarettes smoked (<span class="math inline">\(x\)</span>) deviates from my predictor variable <span class="math inline">\({\hat x}\)</span> by an unknown amount. Here we have Berkson errors and <span class="math inline">\(Var({\hat x})&lt;Var(x)\)</span>. With classical errors, <span class="math inline">\(e_c\)</span> does not affect the response: <span class="math inline">\(e_c=1\)</span> implies that I thought I smoked 11 (or 21) cigarettes when in fact I only smoked 10 (or 20) - this imaginary cigarette will not impact my health. With Berkson errors, <span class="math inline">\(e_b\)</span> does affect the response: <span class="math inline">\(e_b=1\)</span> implies that I smoked one more cigarette than I was told to and this very real cigarette may well impact my health. The consequence of this is that if I use <span class="math inline">\(\hat{x}\)</span> as a predictor in a regression the estimated coefficient will be biased towards zero (attenuated) with classical errors but unbiased with Berkson errors. To see this, note that in both cases the causal model is <span class="math inline">\(y = \beta x+e\)</span> and the regression coefficient that we would expect to obtain had we measured <span class="math inline">\(x\)</span> perfectly would be <span class="math inline">\(E[\hat{\beta}] = \beta =Cov(y,x)/Var(x)\)</span>. With classical error <span class="math inline">\(Cov(y, x+e_c)=Cov(y,x)\)</span> since <span class="math inline">\(e_c\)</span> does not affect the response. However, <span class="math inline">\(Var(x+e_c)=Var(x)+Var(e_c)\)</span> and so the regression is downwardly biased:</p>
<p><span class="math display">\[E_c[\hat{\beta}] = \frac{Cov(y,x)}{Var(x)+Var(e_c)}= \beta\frac{Var(x)}{Var(x)+Var(e_c)}\]</span></p>
<p>The estimated regression coefficient is equal to the true coefficient multiplied by the repeatability of the measurements. Since the repeatability lies between zero and one the estimate is attenuated.</p>
<p>With Berkson error, the causal model <span class="math inline">\(y = \beta x+e\)</span> results in <span class="math inline">\(y = \beta(\hat{x}+e_b)+e\)</span> and so the covariance between <span class="math inline">\(y\)</span> and <span class="math inline">\(\hat{x}\)</span> is <span class="math inline">\(\beta Var(\hat{x})\)</span> and the estimated regression will be:</p>
<p><span class="math display">\[E_b[\hat{\beta}] = \frac{\beta Var(\hat{x})}{Var(\hat{x})}=\beta\]</span></p>
<p>The effects of the extra or fewer cigarettes smoked will appear in the residuals and the residual variance will be estimated as <span class="math inline">\(\beta^2Var(e_b)+Var(e)\)</span>. As in meta-analysis, if the magnitude of <span class="math inline">\(e_b\)</span> varies over patients and we have information about this - for example, we monitor a subset of patients carefully and we know exactly how many cigarettes they smoked - then modelling the Berkson errors can increase the precision of the estimate.</p>

</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="44">
<li id="fn44"><p>To obtain the pooled standard deviation a weighted variance needs to be calculated. For two groups, the weighted variance is <span class="math inline">\(\frac{w_1\widehat{\sigma^2_1}+w_2\widehat{\sigma^2_2}}{w_1+w_2}\)</span> where the <span class="math inline">\(\widehat{\sigma^2}\)</span> are estimates of the variance within each group. The weights are typically the sample size for each group minus one. The pooled standard deviation is the square root of the weighted variance and is the best estimate of the standard deviation under the assumption that it is the same in the two groups.<a href="measurement.html#fnref44" class="footnote-back">↩︎</a></p></li>
<li id="fn45"><p>It might not be clear why this works. In our standard meta-analysis model we used the random formula <span class="math inline">\(\texttt{idh(sqrt(vi)):units}\)</span>. As was covered in Chapters <a href="cat-int.html#cat-int">5</a> and <a href="cont-int.html#cont-int">6</a>, the term inside the variance function, in this case <span class="math inline">\(\texttt{sqrt(vi)}\)</span>, should be treated as a model formula with the intercept removed. The model term therefore determines a slope parameter for the covariate <span class="math inline">\(\sqrt{\texttt{vi}}\)</span>. This slope parameter is allowed to vary across levels of the predictor that is interacted with the variance structure, in this case <span class="math inline">\(\texttt{units}\)</span>. Since each observation is associated with a unique level of <span class="math inline">\(\texttt{units}\)</span> the random effect model prediction for observation <span class="math inline">\(i\)</span> is <span class="math inline">\(\sqrt{\texttt{vi}_i}u_{i}\)</span>. The marginal distribution of <span class="math inline">\(\sqrt{\texttt{vi}_i}u_{i}\)</span> is normal with zero mean and variance <span class="math inline">\(\texttt{vi}_i\sigma^2_u\)</span>. Setting <span class="math inline">\(\sigma^2_u=1\)</span>, the marginal distribution for the measurement error associated with observation <span class="math inline">\(i\)</span> is normal with zero mean and variance <span class="math inline">\(\texttt{vi}_i\)</span>, as desired.</p>
<p>In the multivariate meta-analysis model we used the random formula <span class="math inline">\(\texttt{us(outcome:sqrt(vi)):study}\)</span>. Since <span class="math inline">\(\texttt{outcome}\)</span> has two levels, the term inside the variance function, <span class="math inline">\(\texttt{outcome:sqrt(vi)}\)</span>, defines two parameters: a slope for <span class="math inline">\(\texttt{math}\)</span> and a slope for <span class="math inline">\(\texttt{verbal}\)</span>. These slopes are allowed to vary across studies since <span class="math inline">\(\texttt{study}\)</span> is interacted with the variance function. Consequently, for each study there are two slopes. These slopes are allowed to covary since a <span class="math inline">\(\texttt{us}\)</span> structure was used. Imagine observations <span class="math inline">\(k\)</span> and <span class="math inline">\(l\)</span> are the <span class="math inline">\(\texttt{math}\)</span> and <span class="math inline">\(\texttt{verbal}\)</span> scores from study <span class="math inline">\(j\)</span>. If we designate the slopes for study <span class="math inline">\(j\)</span> as <span class="math inline">\(u^{(\texttt{math})}_j\)</span> and <span class="math inline">\(u^{(\texttt{verbal})}_j\)</span>, the random effect model prediction for observations <span class="math inline">\(k\)</span> and <span class="math inline">\(l\)</span> are <span class="math inline">\(u^{(\texttt{math})}_j\sqrt{\texttt{vi}_k}\)</span> and <span class="math inline">\(u^{(\texttt{verbal})}_j\sqrt{\texttt{vi}_l}\)</span>. The marginal variances of these two predictions are <span class="math inline">\(\sigma^2_\texttt{math}\texttt{vi}_k\)</span> and <span class="math inline">\(\sigma^2_\texttt{verbal}\texttt{vi}_l\)</span>, respectively. If <span class="math inline">\(\sigma^2_\texttt{math}\)</span> and <span class="math inline">\(\sigma^2_\texttt{verbal}\)</span> are set to one, each observation has the desired distribution for its measurement error, as in the univariate model. The marginal covariance between the observations is <span class="math inline">\(\sigma_{\texttt{math},\texttt{verbal}}\sqrt{\texttt{vi}_k}\sqrt{\texttt{vi}_l}\)</span>, and with <span class="math inline">\(\sigma^2_\texttt{math}=\sigma^2_\texttt{verbal}=1\)</span> the marginal correlation is <span class="math inline">\(\sigma_{\texttt{math},\texttt{verbal}}\)</span>. Consequently, fixing the variances of the slopes to one, and their covariance to 0.66, gives the desired model. We can also set <span class="math inline">\(\sigma^2_\texttt{math}=\sigma^2_\texttt{verbal}=1\)</span> but allow the correlation, <span class="math inline">\(\sigma_{\texttt{math},\texttt{verbal}}\)</span>, to be estimated, as was done in model <span class="math inline">\(\texttt{m.meta5}\)</span><a href="measurement.html#fnref45" class="footnote-back">↩︎</a></p></li>
<li id="fn46"><p>I’m not aware of a name for data like this so I just made one up. If anyone knows of a term already in use for such data please let me know.<a href="measurement.html#fnref46" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="pedigree.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="path.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["MCMCglmm-course-notes.pdf", "MCMCglmm-course-notes.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
